#ifndef BSP_MACRO_HPP
#define BSP_MACRO_HPP

#include "stm32f10x.h"
#include "stm32f10x_conf.h"

#define RELEASE
#define DEBUG
#undef RELEASE

#define RCC_IRQHANDLER RCC_IRQHandler
#define RCC_IRQ RCC_IRQn

#define LEDS_GPIO_PORT GPIOA

#define USART_GPIO_PORT GPIOA
#define USART_PERIPH USART1
#define USART_IRQHANDLER USART1_IRQHandler
#define USART_IRQ USART1_IRQn
#define USART_GPIO_TX_PIN GPIO_Pin_9
#define USART_GPIO_RX_PIN GPIO_Pin_10

#define ADC_SPI_PERIPH SPI1
#define ADC_SPI_GPIO_PORT GPIOA
#define ADC_SPI_IRQ SPI1_IRQn
#define ADC_SPI_IRQHANDLER SPI1_IRQHandler
#define ADC_SPI_GPIO_MISO_PIN GPIO_Pin_6
#define ADC_SPI_GPIO_MOSI_PIN GPIO_Pin_5
#define ADC_SPI_GPIO_SCK_PIN GPIO_Pin_7

#define FPGA_EN_GPIO_PORT GPIOB
#define FPGA_EN_GPIO_PIN GPIO_Pin_11

#define FPGA_CMD_DATA_GPIO_PORT GPIOC
#define FPGA_CMD_GPIO_PIN0 GPIO_Pin_8
#define FPGA_CMD_GPIO_PIN1 GPIO_Pin_9
#define FPGA_CMD_GPIO_PIN2 GPIO_Pin_10 
#define FPGA_CMD_GPIO_PIN3 GPIO_Pin_11
#define FPGA_CMD_GPIO_PIN4 GPIO_Pin_12
#define FPGA_CMD_GPIO_PIN5 GPIO_Pin_13
#define FPGA_CMD_GPIO_PIN6 GPIO_Pin_14

#define FPGA_DATA_GPIO_PIN0 GPIO_Pin_0
#define FPGA_DATA_GPIO_PIN1 GPIO_Pin_1
#define FPGA_DATA_GPIO_PIN2 GPIO_Pin_2
#define FPGA_DATA_GPIO_PIN3 GPIO_Pin_3
#define FPGA_DATA_GPIO_PIN4 GPIO_Pin_4
#define FPGA_DATA_GPIO_PIN5 GPIO_Pin_5
#define FPGA_DATA_GPIO_PIN6 GPIO_Pin_6
#define FPGA_DATA_GPIO_PIN7 GPIO_Pin_7

#define DISPLAY_SEG_DIG_0_GPIO_PORT GPIOA
#define DISPLAY_DIG_1_3_GPIO_PORT GPIOB

#define DISPLAY_GPIO_SEG_A_PIN GPIO_Pin_0
#define DISPLAY_GPIO_SEG_B_PIN GPIO_Pin_1
#define DISPLAY_GPIO_SEG_C_PIN GPIO_Pin_2
#define DISPLAY_GPIO_SEG_D_PIN GPIO_Pin_3
#define DISPLAY_GPIO_SEG_E_PIN GPIO_Pin_8
#define DISPLAY_GPIO_SEG_F_PIN GPIO_Pin_11
#define DISPLAY_GPIO_SEG_G_PIN GPIO_Pin_12

#define DISPLAY_GPIO_DIG_0_PIN GPIO_Pin_15
#define DISPLAY_GPIO_DIG_1_PIN GPIO_Pin_0
#define DISPLAY_GPIO_DIG_2_PIN GPIO_Pin_1
#define DISPLAY_GPIO_DIG_3_PIN GPIO_Pin_3

#define DISPLAY_TIM_PERIPH TIM2
#define DISPLAY_TIM_IRQ TIM2_IRQn
#define DISPLAY_TIM_IRQHANDLER TIM2_IRQHandler

#define BUTTONS_GPIO_PORT GPIOB
#define BUTTONS_GPIO_PORTSOURCE GPIO_PortSourceGPIOB

#define BUTTON_MINUS_GPIO_PIN GPIO_Pin_4
#define BUTTON_MINUS_GPIO_PINSOURCE GPIO_PinSource4
#define BUTTON_MINUS_EXTI_LINE EXTI_Line4
#define BUTTON_MINUS_IRQ EXTI4_IRQn
#define BUTTON_MINUS_IRQHANDLER EXTI4_IRQHandler

#define BUTTON_RUN_GPIO_PIN GPIO_Pin_5
#define BUTTON_RUN_GPIO_PINSOURCE GPIO_PinSource5
#define BUTTON_RUN_EXTI_LINE EXTI_Line5
#define BUTTON_RUN_PLUS_IRQ EXTI9_5_IRQn
#define BUTTON_RUN_PLUS_IRQHANDLER EXTI9_5_IRQHandler
 
#define BUTTON_PLUS_GPIO_PIN GPIO_Pin_6
#define BUTTON_PLUS_GPIO_PINSOURCE GPIO_PinSource6
#define BUTTON_PLUS_EXTI_LINE EXTI_Line6

#define BUTTONS_TIM_PERIPH TIM3
#define BUTTONS_TIM_IRQ TIM3_IRQn
#define BUTTONS_TIM_IRQHANDLER TIM3_IRQHandler

#define DAC_GPIO_PORT GPIOA
#define DAC_PERIPH DAC
#define DAC_GPIO_PIN GPIO_Pin_4

#define CHANNELS_NUMBER 35

#endif /* BSP_MACRO_HPP */
